<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <Platforms>x64</Platforms>
        <LangVersion>6</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateNeutralResourcesLanguageAttribute>false</GenerateNeutralResourcesLanguageAttribute>
        <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute> 
        <IsPublishable>false</IsPublishable>
        <RootNamespace>MarcoZechner.ConfigAPI</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Mal.Mdk2.ModAnalyzers" Version="*" />
        <PackageReference Include="Mal.Mdk2.References" Version="*" />
    </ItemGroup>
    <ItemGroup>
        <Compile Include="..\Consumer\Mz.ConfigAPI.Consumer\**\*.cs" Link="Consumer\%(RecursiveDir)%(Filename)%(Extension)" />
        <Compile Remove="Scripts\ConfigAPI\Client\**\*.cs" />
        <Compile Remove="Scripts\ConfigAPI\Main\**\*.cs" />
        <Compile Remove="Scripts\ConfigAPI\Shared\**\*.cs" />
    </ItemGroup>
</Project>
